### ISSUE TITLE
Locales Support

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#1]
### Description

Add locales support

### Proposed solution

Generate data via google translate?

### Alternatives considered

?

### Do you want to create a pull request?

No

**Comment by shhdharmen** [comment]
I can check this.

**Comment by iamandrewluca** [comment]
I saw PR related to this issue. That's very cool that we can use Google Translate to translate. But in terms of library API, how this will work taking into consideration that needs to be tree shakeable? 🤔 

```ts
import { locale } from '@ngneat/falso'

// Something like this?
locale('en')
```

**Comment by NetanelBasal** [comment]
Yes, the next step should be the third option using second entry points.

**Comment by iamandrewluca** [comment]
I can take a look at this later this week. Maybe I'll combine what was done in related PR, and give credits

**Comment by NetanelBasal** [comment]
@theryansmee do you think you can handle this?

**Comment by theryansmee** [comment]
@NetanelBasal - Sorry I don't have any experience with this. It would probably be better suited for someone else.

**Comment by iamandrewluca** [comment]
What would be the approach here. Using [fileReplacements](https://nx.dev/next/build#filereplacements) to replace default locale e.g. `en.json` with `de.json` and do builds for each locale?

**Comment by NetanelBasal** [comment]
We don't want it as a separate npm package. The goal is to import it as: `import { randName } from @ngneat/falso/locales/ru`

**Comment by NetanelBasal** [comment]
Yes, but they will be imported from the main package

**Comment by iamandrewluca** [comment]
Main folder will be something like this
<img width="685" alt="image" src="https://user-images.githubusercontent.com/1881266/153405777-674bf000-a8c1-4fff-9c24-7ee8af1777cb.png">

And each locale subfolder, something like this 🤔 

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1881266/153405918-11371cff-a925-408e-b1d3-670ddc041dfc.png">

**Comment by NetanelBasal** [comment]
yes

**Comment by michaelxvoelker** [comment]
I started to work on it. Would provide a draft PR over the weekend. 😊

**Comment by irg1008** [comment]
Hi I am sorry but the only random value exported from locales seems to be "randomBird". Is this right?
