### ISSUE TITLE
Random hex and RGBA color generator

### ISSUE THREAD

**Issue by raisiqueira** [ngneat/falso#11]
### Description

Add support to generate hexadecimal and RGBA color generator.

### Proposed solution

Generate a random color with hexadecimal or RGBA utility.

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Thanks

**Comment by theryansmee** [comment]
@raisiqueira would it be worth passing an alpha param to the rgb function with default of false? 

Most of the logic will be same other than the alpha

**Comment by NetanelBasal** [comment]
Yes, makes sense to me. `rgb(alpha = false)`

**Comment by NetanelBasal** [comment]
@raisiqueira please do `rgb({ alpha: boolean })`

**Comment by raisiqueira** [comment]
@NetanelBasal @theryansmee The alpha could be a number, like `rgb(255, 1, 180, 1)` or `rgb(255, 1, 180, .2)`;

**Comment by NetanelBasal** [comment]
Yes, my bad.
