### ISSUE TITLE
randSvgIcon

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#114]
### Description

20 free small svg icons

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@theryansmee time for your magic

**Comment by theryansmee** [comment]
Im happy to have a look but I've got a busy start to my week so if anyone else wants to pick it up between now and Wednesday, I'll get the next one

**Comment by NetanelBasal** [comment]
Sure

**Comment by alinp25** [comment]
Should the SVGs be stored as full <path /> elements, or just store their drawing path?

**Comment by NetanelBasal** [comment]
Full elements

**Comment by alinp25** [comment]
I can take it, if possible.

**Comment by alinp25** [comment]
How should the SVG be returned? As strings, containing the SVG element?

**Comment by NetanelBasal** [comment]
Yes
