### ISSUE TITLE
randSinger

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#133]
### Description

100 singers

### Do you want to create a pull request?

No

**Comment by Technologeek** [comment]
@NetanelBasal Assign this to me please? Thanks! I love music

**Comment by Technologeek** [comment]
@theryansmee Sorry for the delay with this just got back from some impromptu travel will PR today/tomorrow!

**Comment by theryansmee** [comment]
@Technologeek - Take your time, no rush. We are all just doing our best with the time we have available 😊
