### ISSUE TITLE
Random super hero

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#134]
### Description

Function that returns random super hero’s 

### Proposed solution

Option 1:
- Standard randSuperheroName() function pulling from simple string array 

Option 2:
- Json data with more info about the hero (name, alter ego, franchise etc) 
- We could then have an assortment of methods (randSuperheroName(), randSuperheroEntity())

I quite like option 2 

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
So both :)

`randSuperheroName(), randSuperhero()`

**Comment by theryansmee** [comment]
Awesome! 😊
