### ISSUE TITLE
Code snippets are not visible in dark mode

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#139]
### Is this a regression?

No

### Description

The code colours not contrasting enough in dark mode meaning they are unreadable (Especially the key names).

![image](https://user-images.githubusercontent.com/7142779/150994774-5a5415ab-5a72-4781-92b5-7bc1dcbf0b57.png)

### Do you want to create a pull request?

Yes

**Comment by theryansmee** [comment]
@NetanelBasal - When I try to run `yarn start` in the docs directory, I get the following error `Module not found: Error: Can't resolve './falso.min' in '/falso/docs/src/theme/ReactLiveScope'`. Is there any prerequisites I need before working on the docs?
_(Sorry if this is a super simple question - I've never worked with react/doc before)_

**Comment by shaharkazaz** [comment]
@theryansmee run from the root `yarn start:docs`

**Comment by theryansmee** [comment]
@shaharkazaz thanks for the heads up. Sorry to keep coming back but I'm now getting: `Module not found: Error: Can't resolve 'seedrandom' in '/falso/docs/src/theme/ReactLiveScope'`

**Comment by shaharkazaz** [comment]
@theryansmee just ran it and seems to be working with no issues 🤷‍♂️

**Comment by theryansmee** [comment]
Strange. From the `mian` branch? I'll remove my packages and start again, maybe theres some old packages or something

**Comment by shaharkazaz** [comment]
Yes, from main

**Comment by shaharkazaz** [comment]
@theryansmee LMK if you managed, I'm here to help 🙂

**Comment by theryansmee** [comment]
@shaharkazaz Nah, I didn't manage it last night. I'm going to try again today. 

From checking out a fresh instance of the project, what are the steps you take to get to the point of being able to run `yarn start:docs` at route?

This is what I get when I run it:
```
Ryans-MBP:falso ryansmee$ yarn start:docs
yarn run v1.10.1
$ npm run build:docs && npm run start --prefix docs

> falso@0.0.0 build:docs /Users/ryansmee/Documents/development/falso
> npm run build && node ./docs-generator.js


> falso@0.0.0 build /Users/ryansmee/Documents/development/falso
> nx build falso && node ./post-build.js


> nx run falso:build 
Bundling falso...
  index.esm.js 349.312 KB
  index.cjs.js 357.48 KB
⚡ Done in 15.11s

———————————————————————————————————————————————

>  NX   SUCCESS  Running target "build" succeeded


Changed umd to cjs

> docs@0.0.0 start /Users/ryansmee/Documents/development/falso/docs
> docusaurus start

[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at http://localhost:3000/falso/.

✖ Client
  Compiled with some errors in 5.02s

(node:9922) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
(Use `node --trace-deprecation ...` to show where the warning was created)


Module not found: Error: Can't resolve 'seedrandom' in '/Users/ryansmee/Documents/development/falso/docs/src/theme/ReactLiveScope'
client (webpack 5.66.0) compiled with 1 error
```

Cheers for your help 😊

**Comment by NetanelBasal** [comment]
@theryansmee use node v16 or go to also library package and run npm i

**Comment by shaharkazaz** [comment]
@theryansmee I'll try a fresh project and update back here 👍

**Comment by theryansmee** [comment]
@NetanelBasal @shaharkazaz - Updating node to v16 and then reinstalling my packages seems to have done the trick. Cheers both of you 👍
