### ISSUE TITLE
Allow an array instead of a single value

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#14]
### Description

Currently, each function returns a single value. We should give the option to return an array of values.

### Proposed solution

Create a proxy function and use it in each one of the function generators:

```ts
export function cat(options?: FakeOptions) {
  return fake(catsData, options)
}
```

```ts
// core.ts
export interface FakeOptions {
  size: number
}

export function fake(options?: { size: 10 } ) {
  return ...
}
```

### Do you want to create a pull request?

No

**Comment by iamandrewluca** [comment]
As of API. I would consider to have a plural method for this

e.g.

```ts
import { randomNumber, randomNumbers } from 'falso'

randomNumber() // single number
randomNumbers({ size: 10 }) // array with 10 random numbers
```
