### ISSUE TITLE
Add lorem ipsum type text block with character count

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#15]
### Description

It would be good to be able to determine a character count for a block of text. This could be super useful for testing max/min validation on inputs

### Proposed solution

We could either update an existing function to take an optional `characterCount` param (maybe `text` or `words`). Or we could create a new function entirely?

E.G
```ts
function text(characterCount = 200): string {
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Yes, we can do `text({ characterCount: number })`

**Comment by theryansmee** [comment]
Ok cool. If you assigned this to me, i'll get that implemented

**Comment by NetanelBasal** [comment]
You can make the changes now according to our new code style, please
