### ISSUE TITLE
rand([1,2,3], {length: 2})

### ISSUE THREAD

**Issue by tomalaforge** [ngneat/falso#152]
### Description

random function which return an array of randum element of given array

I can implemented it if not already done or accepted

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
Do you mean`rand[1, 2, 3]`?

**Comment by NetanelBasal** [comment]
![image](https://user-images.githubusercontent.com/6745730/151920153-fed7a9d6-1bdd-4e26-8115-8c136f816d0a.png)

**Comment by tomalaforge** [comment]
Hi netaniel,

I mean rand([1,2,3], {length: 4}) which return [1,3,2,1]

**Comment by NetanelBasal** [comment]
You can create a PR

**Comment by tomalaforge** [comment]
great, i'll do it tonight, how do I assign myself to this issue?
