### ISSUE TITLE
randEmail creates invalid emails

### ISSUE THREAD

**Issue by yuvalmono** [ngneat/falso#153]
### Is this a regression?

No

### Description

Generating mail with randEmail can generate emails such as: lukasz.ágústsson@hotmail.info which are not valid (in most cases).
maybe create a flag for enabling those characters (such as á). could be applied to all of the name generators.

### Please provide the exception or error you saw

```true
A part followed by '@' should not contain the symbol 'á'
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@theryansmee please take care

**Comment by theryansmee** [comment]
On it
