### ISSUE TITLE
'Edit this page' link not working as expected

### ISSUE THREAD

**Issue by Parikshit-Hooda** [ngneat/falso#161]
### Is this a regression?

No

### Description

To edit a page using the <b>Edit this page</b> link in https://ngneat.github.io/falso/docs/vehicle (and similar pages), it routes to https://github.com/ngneat/falso/docusaurus/edit/main/website/docs/auto-generated/vehicle.mdx . This link is not working a expected. Ideally, it should open a console or editor to edit the page or something like this.

### Please provide a link to a minimal reproduction of the bug

https://github.com/ngneat/falso/docusaurus/edit/main/website/docs/auto-generated/vehicle.mdx

### Please provide the exception or error you saw

```true
Clicking on 'Edit this page'(for Vehicle entity, [this is target](https://github.com/ngneat/falso/docusaurus/edit/main/website/docs/auto-generated/vehicle.mdx)) link at the bottom of the page for an entity, say [vehicle](https://ngneat.github.io/falso/docs/vehicle) is not working.
```

### Please provide the environment you discovered this bug in

```true
GitHub on Brave browser.
```

### Anything else?

Any advice on triaging this bug is appreciated.

### Do you want to create a pull request?

Yes

**Comment by shaharkazaz** [comment]
@NetanelBasal Since these pages are auto-generated according to the JSDoc, where would we like them to lead? I think that maybe a contribution page explaining how to update the docs.

**Comment by NetanelBasal** [comment]
Ok
