### ISSUE TITLE
Exposed ApiId and ApiKey in docusaurus.config.js

### ISSUE THREAD

**Issue by Parikshit-Hooda** [ngneat/falso#167]
### Is this a regression?

No

### Description

Exposed ApiId and ApiKey values in [docusaurus.config.js](https://github.com/ngneat/falso/blob/main/docs/docusaurus.config.js)

### Please provide a link to a minimal reproduction of the bug

https://github.com/ngneat/falso/blob/main/docs/docusaurus.config.js

### Please provide the exception or error you saw

```true
Exposed credentials.
```

### Please provide the environment you discovered this bug in

```true
Brave browser.
```

### Anything else?

Is this a safe behavior? I actually haven't researched on whether this is a pattern or anti-pattern but typically such credentials are not exposed.

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
You can't do anything with these. Thanks for the suggestion.
