### ISSUE TITLE
randFullName is in Address docs.

### ISSUE THREAD

**Issue by yuvalkarif** [ngneat/falso#169]
### Is this a regression?

No

### Description

randFullName is apparent in the address funcs section in the docs (and link is broken)
![image](https://user-images.githubusercontent.com/34835592/152675460-01b57bdf-4509-44ff-b4da-25882a82953d.png)

### Please provide a link to a minimal reproduction of the bug

https://ngneat.github.io/falso/docs/address#randfullname

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
It should be fine now. Thanks.
