### ISSUE TITLE
randomNumber/int/Float: min/max

### ISSUE THREAD

**Issue by mfulton26** [ngneat/falso#20]
### Description

I'd like to be able to get a random number (int or float) between a lower (inclusive) and an upper (exclusive) bound or something similar.

### Proposed solution

- possibly deprecate/rename `randomNumber` to `randomInt`
- add optional arguments to `randomNumber`/`randomInt` and to `randomFloat` to accept an inclusive minimum and an exclusive maximum
- update them to return values only within those ranges

### Alternatives considered

I did briefly look at the implementations of `randomNumber` and `randomFloat` and it appears that instead of generating random number on demand those modules take an approach of having pre-canned items to randomly pick from… that wasn't what I initially expected but I imagine there are benefits to this approach and I'm not sure yet if the same is feasible with a min/max

### Do you want to create a pull request?

I am open to that. I do not feel strongly one way or the other as to who creates the pull request.

**Comment by NetanelBasal** [comment]
`randomFloat` will be added by #11. You can modify the `randomNumber`, change it to a function and support `min` and `max`.

**Comment by mfulton26** [comment]
`randomNumber` still needs updating to support a min and max, correct? Any objections to renaming the function to `randomInt`? (Like `parseInt` and `parseFloat` as floats are numbers too.)

**Comment by mfulton26** [comment]
perhaps then it is just the readme that doesn't show `randomNumber` takes options; thanks!
