### ISSUE TITLE
Wrong sports category in JSON

### ISSUE THREAD

**Issue by rothsandro** [ngneat/falso#201]
### Is this a regression?

No

### Description

The `randSports()` function accepts the category "winterOlympic":

```
// 'olympic' | 'outdoor' | 'winterOlympic';
randSports({ category : 'winterOlympic' });
```

The JSON uses "olympicWinter" but should be "winterOlympic".

Interface: https://github.com/ngneat/falso/blob/main/packages/falso/src/lib/sports.ts#L6
JSON: https://github.com/ngneat/falso/blob/main/packages/falso/src/lib/sports.json#L50

### Please provide the exception or error you saw

```
No Sports found for selected category (winterOlympic)
```

### Do you want to create a pull request?

Yes

**Comment by Pranomvignesh** [comment]
@NetanelBasal please assign this issue to me. I will fix it

**Comment by theryansmee** [comment]
> @NetanelBasal please assign this issue to me. I will fix it

Wait sorry @rothsandro, you want to pick it up as you raised it
