### ISSUE TITLE
random number

### ISSUE THREAD

**Issue by mfulton26** [ngneat/falso#21]
### Description

I see that `randomNumber` and others don't actually generate random numbers on demand but have a pre-canned list of numbers to pick from. I'd like something similar for dates.

### Proposed solution

- `randomDate` returns any random `Date` picking from a pre-canned list of `Date` offsets and then creating a new `Date` object from "now" and applying the offset to get a random `Date` relative to today (the date may be in the future or the past)
- `randomPastDate` does the same as `randomDate` except the offset is always negative to create a `Date` in the past
- `randomFutureDate` is like `randomPastDate` except the offset is always positive
- `randomRecentDate` and `randomSoonDate` are like `randomPastDate` and `randomFutureDate` except using a list of smaller offset values to returns dates that are within a few days from today

### Do you want to create a pull request?

Yes

**Comment by geromegrignon** [comment]
Hey @mfulton26,

About Dates, I'm already working on a PR (tracked with #2 as indicated by Netanel).
I'll submit it today.
