### ISSUE TITLE
randText is invalid

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#221]
### Is this a regression?

No

### Description

<img width="670" alt="image" src="https://user-images.githubusercontent.com/6745730/158028769-34babf0f-83b3-4daa-bfd1-936f1a044536.png">

We have dot and comma. It also doesn't look like text :)

`randText({ length: 300 })`

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@theryansmee

**Comment by theryansmee** [comment]
@NetanelBasal - I've just looked at this and it's behaving correctly. It's given you an array of 300 `randText` each with a fullstop on the end
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/7142779/158032781-855346ea-7ecc-4ae2-9bd3-fe791f9a7f55.png">

Did you mean to use `randText({ charCount: 300 })`?
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/7142779/158032803-29b7dea7-9e1b-4041-80bd-31ffec52ecf7.png">

**Comment by NetanelBasal** [comment]
You're right. That's my bad, sorry for the trouble :)
