### ISSUE TITLE
randInList

### ISSUE THREAD

**Issue by MathRobin** [ngneat/falso#224]
First, many thanks for your work and the great doc^^

### Description

Being able to define a list of words (or whatever) and provides one of them

### Proposed solution

```
falso.randInList(['foo', 'bar']);
// foo
falso.randInList(['foo', 'bar']);
// bar

```

### Do you want to create a pull request?

No

**Comment by leon** [comment]
in the core package there is a `randElement` that takes an array.

could we export that?

**Comment by rothsandro** [comment]
Isn't that the same as the already existing `rand()` function ([docs](https://ngneat.github.io/falso/docs/general/#rand))?

**Comment by theryansmee** [comment]
@rothsandro - Ah yeah, great shout! I'll close this then 😊

**Comment by MathRobin** [comment]
Didn't saw it. Exactly what I wanted. Many thanks!
