### ISSUE TITLE
Make falso available in doc site

### ISSUE THREAD

**Issue by MathRobin** [ngneat/falso#225]
### Description

Firstly: many thanks for your work !

Put falso into page of doc, as it, we can test it directly in the doc. Like some on tools (thinking about moment, date-fns, ...)

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
I'm not sure I understand what you mean.

**Comment by MathRobin** [comment]
When you browse doc website, I would love to be able to try falso into devtools of my browser. Maybe it's already the case, but didn't succeed to use it

**Comment by theryansmee** [comment]
This is na interesting concept that i've actually never noticed before.

https://date-fns.org/
<img width="438" alt="image" src="https://user-images.githubusercontent.com/7142779/159245738-97b8605c-cb6f-44db-b746-c121b62aee65.png">

**Comment by MathRobin** [comment]
yep, it's really cool, date-fns, lodash, momentjs, and some other great tool lib provides this ability. And falso is a great tool^^

**Comment by NetanelBasal** [comment]
I'm not sure what's the motivation when you have:

- A live running example of each function
- A stackblitz link

**Comment by NetanelBasal** [comment]
Ok, so @theryansmee already added it 😂

**Comment by theryansmee** [comment]
Hahaha I'm happy not to if you are not a fan 😂 It was only a few lines of code so i'm easy either way mate haha

**Comment by NetanelBasal** [comment]
I'm fine

**Comment by MathRobin** [comment]
Many thanks @theryansmee, many love on you

**Comment by theryansmee** [comment]
😂 we got there eventually haha

**Comment by MathRobin** [comment]
(don't understand your last comment, I don't speak well english :-( , thanks french education )

**Comment by MathRobin** [comment]
![2022-03-21_14-49](https://user-images.githubusercontent.com/1046585/159274848-0a911307-16c6-4082-9799-ad0d75775c5c.png)
:heart:
