### ISSUE TITLE
Allow specifying precision in randNumber

### ISSUE THREAD

**Issue by leon** [ngneat/falso#226]
### Description

in faker i used generating numbers with precision.

```
faker.datatype.number({ min: 100, max: 2000, precision: 100 })
```
which would give me
`1400`

### Proposed solution

Could we add the precision option to randNumber?

### Do you want to create a pull request?

No

**Comment by Pranomvignesh** [comment]
Hi @leon, I have attempted to add this feature in randNumber, but got stuck on one issue.
What if, the precision value is greater than provided max value, then my implementation always outputs 0

I'm not sure whether my implementation is correct (or) not. Also, Correct me if I misunderstood your use case

Check out my implementation of precision [here](https://github.com/Pranomvignesh/falso/blob/f9794db3cb1bb6dd6df6b6b7f81d2c81631d25a6/packages/falso/src/lib/core/core.ts#L45)

**Comment by leon** [comment]
@Pranomvignesh Yes this what I was after :)

the new @fakerjs repo uses this code
https://github.com/faker-js/faker/blob/main/src/datatype.ts#L62-L78

There are a few workarounds in their code we might want to have as well.

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR.

**Comment by Pranomvignesh** [comment]
Hi @leon , Thanks for the clarification.

Upon experimenting on the new fakerjs source code, I found that it also has the flaw which I have mentioned before.

I have created some scenarios where precision will shift the output making it not compliant to the provided min and max values.

Refer the [Code Sandbox Playground](https://codesandbox.io/s/precisioninrandnumber-falso-vs-faker-u5cwhb?file=/index.mjs:0-1842)

```js
import { faker } from '@faker-js/faker';
import { random } from '@ngneat/falso';

// 1. Precision > max
// Constants
let iterations = 1000;
const min = 10, max = 1000, precision = 5000


// Faker Example

const FakerOutputs = [];
const valuesNotInRangeInFaker = [];
let fakerCount = 0;
while (fakerCount++ < iterations) {
  const value = faker.datatype.number({
    min,
    max,
    precision
  })
  if (value < min) valuesNotInRangeInFaker.push(value);
  else if (value > max) valuesNotInRangeInFaker.push(value);
  FakerOutputs.push(value);
}


// Falso Example

const FalsoOutputs = [];
const valuesNotInRangeInFalso = [];
let falsoCount = 0;
// Proposed Solution
function getRandomInRange({
  min = 1.0,
  max = 9999.99,
  fraction = 0,
  precision = 1
}) {
  const randNum = Number((random() * (max - min) + min).toFixed(fraction));
  return Math.floor(randNum / precision) % precision;
}
while(falsoCount++ < iterations){
  const value = getRandomInRange({
    min,
    max,
    precision
  })
  if (value < min) valuesNotInRangeInFalso.push(value);
  else if (value > max) valuesNotInRangeInFalso.push(value);
  FalsoOutputs.push(value)
}


// Results
const errorPercentageInFaker = (valuesNotInRangeInFaker.length / FakerOutputs.length) * 100

const errorPercentageInFalso = (valuesNotInRangeInFalso.length / FalsoOutputs.length) * 100
console.log({
  errorPercentageInFaker,
  errorPercentageInFalso
})

// 2. Precision < min

// Edge Cases where precision will break the code
const edgeCases = [{
  min : 4, max : 5 , precision : 3
},{
  min : 8, max : 13, precision : 7
}]

edgeCases.forEach(({min,max,precision},index)=>{
  console.log("Edge Case "+(index+1));
  console.log("Faker", faker.datatype.number({
    min,
    max,
    precision
  }))
  console.log("Falso",getRandomInRange({
    min,
    max,
    precision
  }))
})

```

The edgeCases here are carefully created in such a way that it will break the generator code and I believe that this won't be a practical use case for an user.

So I think, logging an **error** (or) **warning** message if the precision doesn't fall into the min-max range, would be better.

@NetanelBasal , is it advisable to add such logs in falso's functions ? Is there any recommended way of informing the user about the issue in the provided options ?

**Comment by leon** [comment]
I submitted a PR for it 🚀 
https://github.com/ngneat/falso/pull/230

**Comment by leon** [comment]
Fixed by: https://github.com/ngneat/falso/pull/230
