### ISSUE TITLE
uuid does not implement seed

### ISSUE THREAD

**Issue by leon** [ngneat/falso#232]
### Is this a regression?

No

### Description

When using `randUuid` is used `uuid` under the hood.
But it generates new values even if you have set a seed.

I think we could fix it by passing along a random parameter to the uuid function.
but it requires a `InputBuffer` with 16 bytes of random data.

I'm not sure how to best generate 16 bytes of random data based on the `seedrandom` library.

Any suggestions?

in that case I could create a PR.

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
@leon any news here?

**Comment by leon** [comment]
No sorry
I will not have the time to fix it.
