### ISSUE TITLE
Possibility to set finance account length

### ISSUE THREAD

**Issue by pumano** [ngneat/falso#236]
### Description

I'm trying to migrate from faker to falso, and stuck with finance account, because faker provide possibility to generate account with any length, for example: `finance.account(10)` create random account with 10 digits, but when I use length in falso account I only can use it for create array of accounts. 

### Proposed solution

I check code:
https://github.com/ngneat/falso/blob/119af8da17a77eaa18fc22ecc7628099d07846c4/packages/falso/src/lib/account.ts#L21-L23

And looks like length is hardcoded, could you please provide parameter for changing length of account? Because in some cases I need different length, but currently only 9 digits. I can prepare pull request if needed.

### Do you want to create a pull request?

Yes

**Comment by shaharkazaz** [comment]
@pumano Would love to see your PR 🙂
