### ISSUE TITLE
Combining an helper with a random length isn't consistent

### ISSUE THREAD

**Issue by davidfou** [ngneat/falso#253]
### Is this a regression?

No

### Description

Combining an helper with `randNumber` for the length gives inconsistent output. Whenever the length is `0`, the output is no longer an array:

```js
const { randNumber } = require("@ngneat/falso");

// expect numbers to be an array of integers
const numbers = randNumber({ length: randNumber({ min: 0, max: 5, precision: 1 });
```

### Please provide a link to a minimal reproduction of the bug

https://runkit.com/dfournier/bug-falso

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
You're welcome to submit a PR
