### ISSUE TITLE
randWord sometimes generates one letter

### ISSUE THREAD

**Issue by Hypenate** [ngneat/falso#260]
### Is this a regression?

No

### Description

When using randWord() it sometimes only gives you one letter, a letter is not a word.

![image](https://user-images.githubusercontent.com/7478681/167408686-5d13db6e-eec7-44b2-a9f6-c6b6367ff5f4.png)

### Anything else?

If you agree, I can do a PR.
A quick check if the length > 1 can be sufficient, if not we regenerate

I don't think there is another way because falso uses Fako?

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Sure, go ahead.
