### ISSUE TITLE
Support gender for lastname / firstname generation

### ISSUE THREAD

**Issue by pumano** [ngneat/falso#262]
### Description

Would love if we can use parameter with gender in `randLastName()` and `randFirstName()`:

```ts
randLastName({ gender: 'male' }); // Smith

randFirstName({ gender: 'female' }); // Emma
```

### Proposed solution

We need to sort current first names / last names by gender in `json` file including option `withAccents` and then add parameter gender with `male | female` types.

@NetanelBasal how do you think about it?

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
It seems like a nice feature.

**Comment by pumano** [comment]
@NetanelBasal OK I will try to prepare PR soon

**Comment by theryansmee** [comment]
My only thought is that our genders in falso are not binary. See packages/falso/src/lib/gender.json

**Comment by theryansmee** [comment]
Also, I'm not sure about in other cultures but I don't think last names are gendered?

**Comment by pumano** [comment]
@NetanelBasal @theryansmee In some cases, it's relevant. Check out Ivanova, Ivanov and etc for last names.

**Comment by NetanelBasal** [comment]
Yes, but I don't think it's a common use case.

**Comment by pumano** [comment]
@NetanelBasal OK I will add option for pass gender to lastname, but in implementation for common usecase I do nothing with it, but in i18n case I process it as needed for case I need, OK?

**Comment by NetanelBasal** [comment]
ok
