### ISSUE TITLE
`rand` Should Likely Support `readonly` Arrays/Tuples

### ISSUE THREAD

**Issue by joealden** [ngneat/falso#275]
### Is this a regression?

No

### Description

Take the following example:

```ts
import { rand } from "@ngneat/falso";

const values = ["a", "b", "c"] as const;
const randomValue = rand(values);
```

Typescript returns the following type error at the `rand` callsite:

> The type 'readonly ["a", "b", "c"]' is 'readonly' and cannot be assigned to the mutable type 'unknown[]'.

I believe that this should be supported, as I don't think this library relies on the array being mutable.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@shaharkazaz is about to create a PR that solves this issue.
