### ISSUE TITLE
Possible random range issue for zero

### ISSUE THREAD

**Issue by tbenade** [ngneat/falso#289]
### Is this a regression?

No

### Description

I was expecting a result of 0 for 
```
randNumber({ 0, 0 });
```
but it returns arbitrary integers. where as 

```
randNumber({ 1, 1 });
```
would return `1`

### Anything else?

Thank you great project.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@shaharkazaz, please fix it as part of the other fix we discussed.
