### ISSUE TITLE
`rand` isn't actually exported

### ISSUE THREAD

**Issue by brandonpittman** [ngneat/falso#29]
### Is this a regression?

Yes

### Description

rand is listed in the README as an export, but it's not actually exported.

I started a [PR](https://github.com/ngneat/falso/pull/28) but the required boilerplate took longer than the fix.

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
I'll release a fix asap

**Comment by NetanelBasal** [comment]
Should be OK now.
