### ISSUE TITLE
Add npm and node version info to package json

### ISSUE THREAD

**Issue by czlowiek488** [ngneat/falso#293]
I don't know what versions of node or npm you are using.
It is a bit tricky to find out exact versions on my own.
I think it may be a good idea to add `engines` field to `package.json` file like in example below.
```json
  "engines": {
    "npm": ">2.0.0",
    "node": ">=0.12.0"
  },
```

It may not been seen so important but in certain circumstances (unknown to me) rebase of package-lock with 2 different versions of npm spawns error.
I've spent many hours discovering that the errror was caused by npm versions difference.

**Comment by NetanelBasal** [comment]
v16.15.1
8.11.0
