### ISSUE TITLE
Data Optimization 

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#3]
### Description

We can minimize the bundle size by using existing functions in other helpers. For example:

```
findName() => firstName() + lastName()
email() => firstName().toLowerCase() + postfix
card
alpha
etc
```

### Proposed solution

...

### Alternatives considered

No

### Do you want to create a pull request?

No

**Comment by theryansmee** [comment]
Would it also be useful to have a way of ensuring you don't get the same name twice in a test?

Maybe we could do something like make FindName a class, then when a name is return it is then removed from the array? _(This would get trickier with `firstName() + lastName()` stuff)_

**Comment by NetanelBasal** [comment]
I think we can introduce something like `uniqe(firstName)`

**Comment by geromegrignon** [comment]
Please assign me this issue

**Comment by NetanelBasal** [comment]
Closing in favor of #35
