### ISSUE TITLE
fraction doesn't work on randAggregation 

### ISSUE THREAD

**Issue by PumpedSardines** [ngneat/falso#305]
### Is this a regression?

No

### Description

When passing in the argument `fraction` to the function `randAggregation` nothing changes

### Please provide the exception or error you saw

```true
Inputing

function Demo(props) {
  return <Preview source={() => randAggregation({ values: 5, fraction: 5 })}/>;
}
```
On the docs page will not provide fractions
```


### Please provide the environment you discovered this bug in

```true
On the docs page
```

### Do you want to create a pull request?

No

**Comment by Parikshit-Hooda** [comment]
Is this still an issue? Should we close this one as I see a PR got merged?

**Comment by shaharkazaz** [comment]
@Parikshit-Hooda I think you are correct
