### ISSUE TITLE
JSON files for Food and Sports not deployed

### ISSUE THREAD

**Issue by Guzikowski** [ngneat/falso#334]
### Is this a regression?

No

### Description

"@ngneat/falso": "^6.3.1"  package does not include food or sports JSON files. This causes the following compilation issues: 

node_modules/@ngneat/falso/lib/food.d.ts:2:22 - error TS2732: Cannot find module './food.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

2 import { data } from './food.json';
                       ~~~~~~~~~~~~~

 using '--resolveJsonModule' to import module with '.json' extension.

2 import { data } from './sports.json';

The files are currently in master, so could fix a local deployment, but CI deployments will need a fix to correct the compilation issue. 



### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true
tsc -b output after deploying latest version

node_modules/@ngneat/falso/lib/food.d.ts:2:22 - error TS2732: Cannot find module './food.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.

2 import { data } from './food.json';
                       ~~~~~~~~~~~~~

 using '--resolveJsonModule' to import module with '.json' extension.

2 import { data } from './sports.json';
```


### Please provide the environment you discovered this bug in

```true
Found this in a local development and in my CI build
```

### Anything else?

Kind of a blocker in that my CI build actions require a clean compilation will need to bypass that guard if I continue using the latest else will need to rollback to 6.2

### Do you want to create a pull request?

No

**Comment by maxiwer** [comment]
I have the same problem, commented out here.
