### ISSUE TITLE
Use everywhere `random` instead of `Math.random`

### ISSUE THREAD

**Issue by iamandrewluca** [ngneat/falso#34]
### Is this a regression?

Yes

### Description

Usage of `Math.random` should be banned because cannot be deterministic.
And in cases when using a faker funtion in a test, it will allways fail, because everytime returns nondeterministic random data.

A `random` method already exists in the source code that allow also to set a `seed` for pseudo random generator.

To replace every instance of `Math.random` with `random` from `random.ts`

```diff
+import { random } from './random.ts
-Math.random()
+random()
```

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
I'll fix it. I didn't release it yet. This will be a part of a new major version with many changes, features, and optimizations. 

@iamandrewluca I've added a lot of `TODO - generate programmatically` if you want to help.
