### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#35]
### Description

# Goals
- Smaller Bundle
- ~Added TODOS to generate the data programmatically in some functions~
- Finalize the API
- ~Create a docs generator~
- Add comments for docs generation.

### Comment Structure:

```ts
/**
 * Generate a random date between ranges.
 *
 * @category Date
 *
 * @example
 *
 * month()
 *
 * @example
 *
 * month({ from: Date, to: Date })
 *
 * @example
 *
 * month({ length: 10 })
 *
 */
export function between<Options extends BetweenOptions>(options: Options) {}
```

# FINAL API

- seed

## General
- randomNumber
- randomFloat
- randomBoolean
- randomImg
- uuid
- locale
- rand

## System
- fileName
- mimeType
- fileType
- fileExt
- directoryPath
- filePath
- semver

## Text
- text
- word
- sentence
- alpha
- alphaNumeric
- slug
- abbreviation
- adjective
- noun
- verb
- ingverb
- phrase

## Jobs
- jobTitle
- jobDescriptor
- jobArea
- jobType

## Internet
- protocol
- httpMethod
- url
- domainName
- domainSuffix
- domainWord
- ip
- ipv6
- port
- userAgent
- mac

## Person
- firstName
- lastName
- fullName
- middleName
- gender
- personPrefix
- phone
- email
- avatar
- password
- userName

## Colors
- rgb
- hex
- hsl

## Date
- past
- future
- between
- recent
- soon
- month
- weekday

# COMMERCE
- department
- productName
- price
- productAdjective
- productMaterial
- product
- productDescription

# Company
Note: Prefix each function with `company` and max 20 items for each

- name
- suffix
- phrase
- catchPhraseAdjective
- catchPhraseDescriptor
- catchPhraseNoun
- bsAdjective
- bsBuzz
- bsNoun

# Database
Note: Prefix each function with `database` and max 20 items for each

- column
- type
- collation
- engine

## Address
- zipCode
- zipCodeByState
- city
- streetName
- streetAddress
- county
- country
- countryCode
- state
- stateAbbr
- latitude
- longitude
- direction
- cardinalDirection
- ordinalDirection
- nearbyGPSCoordinate
- timeZone

## Finance
- account
- routingNumber
- mask
- amount
- transactionType
- currencyCode
- currencyName
- currencySymbol
- bitcoinAddress
- creditCardNumber
- creditCardCVV
- ethereumAddress
- iban
- bic
- transactionDescription

## Git
- branch
- commitEntry
- commitMessage
- commitSha
- shortSha

## Animals
Note: max 20 items for each

- dog
- cat
- snake
- bear
- lion
- cetacean
- horse
- bird
- cow 
- fish
- crocodilia
- insect
- rabbit
- animalType

## Vehicle 
Note: Prefix each function with `vehicle` and max 20 items for each

- manufacturer
- model
- type
- fuel
- vin
- vrm
- bicycle

### Do you want to create a pull request?

No

**Comment by iamandrewluca** [comment]
imo. We should prefix also Date functions 👀

**Comment by NetanelBasal** [comment]
No. To be honest, I don't care about faker.js. This library should be better.

**Comment by NetanelBasal** [comment]
We'll add more options to each function when we finish this part and create new functions.

**Comment by Technologeek** [comment]
@NetanelBasal Can dedicate a few hours next week. Is there anything you can assign to me?

**Comment by theryansmee** [comment]
@NetanelBasal I'm happy to help with adding the comments if no one is already working on that?

**Comment by theryansmee** [comment]
> @NetanelBasal I'm happy to help with adding the comments if no one is already working on that?

Scratch that, it looks like thats already been done?

**Comment by shaharkazaz** [comment]
@Technologeek If it's next week, let's see how we are doing after this weekend. I've done some work 🙂 
@theryansmee It's partially done, some have, and some don't, working on it as well but probably won't finish everything.

**Comment by theryansmee** [comment]
> @Technologeek If it's next week, let's see how we are doing after this weekend. I've done some work 🙂 
> 
> @theryansmee It's partially done, some have, and some don't, working on it as well but probably won't finish everything.

Ok cool. Well I have a block of free time tomorrow, I'm happy to pick up any that you are not going to have time for 😊

**Comment by NetanelBasal** [comment]
Done
