### ISSUE TITLE
angular-cli 19.0.4 starts throw error while vite dev server processing `seedrandom` when using require('crypto')

### ISSUE THREAD

**Issue by pumano** [ngneat/falso#386]
### Is this a regression?

No

### Description

after landing [commit](https://github.com/angular/angular-cli/commit/fc41f50b53bbffead017b420105eed5bd8573ac1) to 19.0.4 angular-cli we got errors in `ng serve` mode. 

Dependency `seedrandom` trying to require('crypto') and that cause problems when processed by `vite`.
`seedrandom` not updated 5 years, looks like logic should patched in falso or implemented from scratch.

### Please provide the exception or error you saw

```true
➜  Local:   http://localhost:4200
  ➜  press h + enter to show help
✘ [ERROR] The package "crypto" wasn't found on the file system but is built into node. [plugin angular-browser-node-built-in]

    node_modules/seedrandom/seedrandom.js:265:27:
      265 │       nodecrypto = require('crypto');
          ╵                            ~~~~~~~~
```

### Do you want to create a pull request?

No

**Comment by wprogeye** [comment]
I also encountered this error. A simple update to angular-cli version 19.1.0-next.0 fixed it.
