### ISSUE TITLE
Generate randLines programmatically

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#39]
### Description

Generate `randLines` programmatically

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@theryansmee it's on you :)

**Comment by theryansmee** [comment]
I'm deffo up for it 😊 
What will make this different to `text()`

**Comment by NetanelBasal** [comment]
Line  breaks - \n

**Comment by theryansmee** [comment]
Perfect. A sign it to me then 😊 

I wonder if as a v2, once we have our various text based functionality defined, we could combine some of them by passing options? 

E.G

 `{ lineBreaks: true }`

For now I think it's right to keep them separate and simple 😊
