### ISSUE TITLE
Randomly generate RGB values

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#4]
### Description

Instead of having an array of static RGB values, we could generate them on the fly.

(I'd be happy to do the work, i've just never contributed to an open source project before so i'm not sure on the etiquette)

### Proposed solution

```ts
function randomValue() {
    return Math.floor(Math.random() * (255 + 1));
}

export function rgb() {
    return `rgb(${randomValue()}, ${randomValue()}, ${randomValue()})`;
}

```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Sounds good. Google on how to contribute to a project ( fork ). Change the code, stage the files, run `yarn c`, answer the questions and open a PR.

**Comment by theryansmee** [comment]
I will do 😊
