### ISSUE TITLE
Product Entity

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#42]
### Description

Add randProduct entity

### Do you want to create a pull request?

No

**Comment by ikerasiotis** [comment]
I could contribute to it if I have more information about the 'Product Entity'. Thank You!

**Comment by NetanelBasal** [comment]
It should return:

```ts
{
  id,
  title,
  description,
  price,
  category,
  image,
  rating: {
    rate: 3.9,
    count:1 20
  }
}
```

**Comment by ikerasiotis** [comment]
It's fine for me! You can assign me if you want! :)

**Comment by ikerasiotis** [comment]
I have a question. Do you want to use `packages/falso/src/lib/product.json` to generate the Entity Object or create a new JSON with generated data?

**Comment by NetanelBasal** [comment]
It should be created based on other functions.

**Comment by ikerasiotis** [comment]
Thank You. I have also one more question. Where may I find _Category_ and _Image_ Attributes?

**Comment by NetanelBasal** [comment]
Oh I see that you'll need to add a new category function :)

As for the image we have a function for this.

**Comment by ikerasiotis** [comment]
No worries. I can add it!! I was confused cause there is a file name product.json.
