### ISSUE TITLE
Add Abbrevation option to gender

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#50]
### Description

`gender({ abbrev: true })` // F M

### Do you want to create a pull request?

No

**Comment by RishiKumarRay** [comment]
I would like to do, can you tell me where in the code, we have to add this

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/falso/blob/main/packages/falso/src/lib/gender.ts

**Comment by RishiKumarRay** [comment]
At which line i have to add? @NetanelBasal

**Comment by RishiKumarRay** [comment]
I am really interested to contribute , just need guidance as i am new to this? if you have any references , please give i will read and then contribute @NetanelBasal

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/falso/blob/main/CONTRIBUTING.md

**Comment by michaelxvoelker** [comment]
@RishiKumarRay Have a look at the language/language-codes implementation: https://github.com/ngneat/falso/pull/66/files 

You can implement gender abbreviations in a similar way. 🙂

**Comment by dsa0x** [comment]
Please assign this to me.
