### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#52]
### Description

Add person skills function

### Do you want to create a pull request?

No

**Comment by NetanelBasal** [comment]
@theryansmee do you want to take this?

**Comment by theryansmee** [comment]
Yeah sure assign it to me 😊

**Comment by NetanelBasal** [comment]
@theryansmee I've added you as a member of this project. You have write access now.

**Comment by theryansmee** [comment]
Thank you! That's really cool 😊
