### ISSUE TITLE
Browsers

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#77]
### Description

Browsers list

### Do you want to create a pull request?

No

**Comment by michaelxvoelker** [comment]
@NetanelBasal Feel free to assign me to #77 #78 #79 #80. I can do them in one PR. 🙂

**Comment by NetanelBasal** [comment]
It's all yours

**Comment by NetanelBasal** [comment]
You'll need to comment in each one of them

**Comment by michaelxvoelker** [comment]
#83
