### ISSUE TITLE
Brands

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#79]
### Description

Brands list

### Do you want to create a pull request?

No

**Comment by michaelxvoelker** [comment]
How is brands list different to companies list? 🤔

**Comment by NetanelBasal** [comment]
https://ig.ft.com/top-100-global-brands/2018/

**Comment by NetanelBasal** [comment]
https://smallbusiness.chron.com/difference-between-company-brand-26198.html

**Comment by michaelxvoelker** [comment]
PR #83 submitted.
