### ISSUE TITLE
Seeded random number generator instead of Math.random

### ISSUE THREAD

**Issue by iamandrewluca** [ngneat/falso#8]
### Description

Right now `falso` generator is nondeterministic.
Using it in some snapshot tests will make tests always fail.

### Proposed solution

Add a way to set a starting seed number for random number generator

Proposed API

```ts
import { seed, randomNumber } from 'falso'

seed('some-seed') // set seed to some constant
randomNumber() // always returns same number
```

https://github.com/davidbau/seedrandom
https://unpkg.com/browse/faker@5.5.3/lib/random.js

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
It's all yours
