### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#80]
### Description

Permissions list

### Do you want to create a pull request?

No

**Comment by dsa0x** [comment]
Hi. I could work on this. what kind of permissions are you referring to though?

**Comment by michaelxvoelker** [comment]
PR #83 submitted.

**Comment by NetanelBasal** [comment]
@dsa0x you can take #50

**Comment by dsa0x** [comment]
OK. Please assign it to me.

**Comment by NetanelBasal** [comment]
You need to comment in the issue
