### ISSUE TITLE
Phone Number Formats

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#84]
### Description

Support formats in phone number function.

References:

https://gist.github.com/anubhavshrimal/75f6183458db8c453306f93521e93d37
https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers

### Do you want to create a pull request?

No

**Comment by ikerasiotis** [comment]
How many do we want? Also, do you want to add locales? I could be on it

**Comment by NetanelBasal** [comment]
You can use the JSON mentioned here. I'm thinking about something like:

```ts
randPhoneNumber({ countryCode: 'AN' }) // +599438438
```

**Comment by NetanelBasal** [comment]
I'm open to suggestions, though.

**Comment by ikerasiotis** [comment]
Do you want to generate from a regex a phone number? I think the length of the string is different country by country. Also, many developers use validator.js, so it should generate a number that passes the function `isMobile()`.

**Comment by NetanelBasal** [comment]
Seems fine to me

**Comment by theryansmee** [comment]
I'm not sure if this is overkill, but i've user [Google phone lib](https://github.com/google/libphonenumber) in the past for validating numbers and its great. I think you can also use it to format numbers from lots of diff places? Could help?

**Comment by NetanelBasal** [comment]
@ikerasiotis I see that @arulprabakaran already did this.

**Comment by ikerasiotis** [comment]
@NetanelBasal. ok..

**Comment by NetanelBasal** [comment]
You're welcome to contribute and add more generators.
