### ISSUE TITLE
Allow user to pass email provider/suffix to randEmail

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#89]
### Description

This would allow user to test regex patterns for specific emails with random names. 

E.G 

```TS
randEmail({ length: 20, provider: 'myCorpEmail', suffix: 'com' });
// -> [ ryan.smee@myCorpEmail.com, tom.smith@myCorpEmail.com, kat.philips@myCorpEmail.com, .... ]
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Cool

**Comment by theryansmee** [comment]
As part of this I have added a randEmailProvider function
