### ISSUE TITLE
Auto generate docs

### ISSUE THREAD

**Issue by NetanelBasal** [ngneat/falso#9]
### Description

Use tool like https://typedoc.org/ to auto-generate our docs

### Do you want to create a pull request?

No

**Comment by ankitverma2211** [comment]
@NetanelBasal can you assign me this issue.

**Comment by NetanelBasal** [comment]
Sure

**Comment by NetanelBasal** [comment]
But wait for the task of @shaharkazaz before you start. He should do this today

**Comment by ankitverma2211** [comment]
okay

**Comment by ankitverma2211** [comment]
@NetanelBasal getting the following error while generating docs . I have the latest code pulled . 
<img width="1106" alt="Screenshot 2022-01-12 at 11 33 05 PM" src="https://user-images.githubusercontent.com/3154730/149196510-8e674421-f3cb-4407-96c9-b00bb90f44be.png">

**Comment by geromegrignon** [comment]
> @NetanelBasal getting the following error while generating docs . I have the latest code pulled . 
> <img width="1106" alt="Screenshot 2022-01-12 at 11 33 05 PM" src="https://user-images.githubusercontent.com/3154730/149196510-8e674421-f3cb-4407-96c9-b00bb90f44be.png">
> 
> 

Run npm install as your installed dependencies aren't matching the pulled package.json

**Comment by ankitverma2211** [comment]
> > @NetanelBasal getting the following error while generating docs . I have the latest code pulled .
> > <img alt="Screenshot 2022-01-12 at 11 33 05 PM" width="1106" src="https://user-images.githubusercontent.com/3154730/149196510-8e674421-f3cb-4407-96c9-b00bb90f44be.png">
> 
> Run npm install as your installed dependencies aren't matching the pulled package.json

Hey, @geromegrignon thanks for responding back quickly. I did do an npm install if you look at the screenshot before running the command. Now I have even deleted the node_modules folder and tried again doing an npm install. It did not work. Let me know if I am missing anything

**Comment by ankitverma2211** [comment]
I got the issue the dep seedrandom was not added to the package.json. I have added it and it now works. Thanks for your input @geromegrignon
