### ISSUE TITLE
Allow users to get names with/without accented characters

### ISSUE THREAD

**Issue by theryansmee** [ngneat/falso#90]
### Description

Not all systems are meant to support accented characters. 

We should separate the firstName and lastName JSON into with/without accented characters and allow users to pass a param to `randFirstName`, `randLastName` & `randFullName`

```
randFullName({ accentedChars: true });
// Alícia Ðekić

randFullName({ accentedChars: false });
// Ryan Smee

randFullName();
// Ryan Ðekić
```

### Do you want to create a pull request?

Yes

**Comment by NetanelBasal** [comment]
Can I say no to you?

**Comment by theryansmee** [comment]
You can, but I might cry haha
